name: C/C++ CI

on:
  push:
    branches: [ "newcpus" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure for release
      run: cd bochs && ./.conf.gh-build-test release && make
    - name: cleanup
      run: make -C bochs all-clean

    - name: configure i686 configuration
      run: cd bochs && ./.conf.gh-build-test i686 && make
    - name: cleanup
      run: make -C bochs all-clean

    - name: configure minimalistic configuration
      run: cd bochs && ./.conf.gh-build-test nothing && make
    - name: cleanup
      run: make -C bochs all-clean

    - name: configure maximum possible configuration
      run: cd bochs && ./.conf.gh-build-test everything && make
    - name: cleanup
      run: make -C bochs all-clean
